Repository sparta-incubating/rchive-back, pull requests merged in 2024-08, with the labels that each got.

#200 [#195] BackOffice: 트랙의 열람 권한 거절하는 기능 추가
  src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
  src/main/java/kr/sparta/rchive/domain/backoffice/respoonse/BackofficeResponseCode.java
  src/main/java/kr/sparta/rchive/domain/bookmark/service/BookmarkService.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/exception/PostExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
  src/main/java/kr/sparta/rchive/domain/user/entity/Track.java
  src/main/java/kr/sparta/rchive/domain/user/service/TrackService.java
  src/main/java/kr/sparta/rchive/global/s3/exception/S3ExceptionCode.java
Labels: enhancement

#209 [#208] Post: 회의 후 post 검색 및 튜터 검색 기능 수정
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/enums/PostSearchTypeEnum.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/post/repository/TagRepository.java
  src/main/java/kr/sparta/rchive/domain/post/repository/TutorRepository.java
  src/main/java/kr/sparta/rchive/domain/post/repository/TutorRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/post/repository/TutorRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
  src/main/java/kr/sparta/rchive/domain/post/service/TutorService.java
Labels: fix

#211 [#207] User관련 Exception 명세서 Swagger에 정리
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
  src/main/java/kr/sparta/rchive/domain/user/exception/statement/ReissueException.java
  src/main/java/kr/sparta/rchive/domain/user/exception/statement/SignupException.java
  src/main/java/kr/sparta/rchive/global/execption/statement/SignupException.java
Labels: enhancement

#214 [#213] Role: 현재 권한 확인 로직 추가
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/global/redis/RedisService.java
Labels: enhancement

#221 [#218] Comment: 게시물의 부모 댓글 조회하는 기능 추가
  src/main/java/kr/sparta/rchive/domain/comment/dto/CommentUserInfo.java
  src/main/java/kr/sparta/rchive/domain/comment/dto/response/CommentGetRes.java
  src/main/java/kr/sparta/rchive/domain/comment/entity/Comment.java
  src/main/java/kr/sparta/rchive/domain/comment/repository/CommentRepository.java
  src/main/java/kr/sparta/rchive/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/comment/repository/CommentRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/comment/service/CommentService.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostCommentCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/repository/TutorRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
Labels: enhancement

#217 [#216] Comment: 댓글 삭제하는 기능 추가
  src/main/java/kr/sparta/rchive/domain/comment/dto/CommentUserInfo.java
  src/main/java/kr/sparta/rchive/domain/comment/dto/response/CommentGetRes.java
  src/main/java/kr/sparta/rchive/domain/comment/entity/Comment.java
  src/main/java/kr/sparta/rchive/domain/comment/repository/CommentRepository.java
  src/main/java/kr/sparta/rchive/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/comment/repository/CommentRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/comment/service/CommentService.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostCommentCoreService.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetSinglePostRes.java
  src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
  src/main/java/kr/sparta/rchive/domain/post/repository/TutorRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
Labels: enhancement

#215 [#212] Comment: 댓글 추가하는 로직 추가
  src/main/java/kr/sparta/rchive/domain/comment/dto/CommentUserInfo.java
  src/main/java/kr/sparta/rchive/domain/comment/dto/request/CommentCreateReq.java
  src/main/java/kr/sparta/rchive/domain/comment/dto/response/CommentGetRes.java
  src/main/java/kr/sparta/rchive/domain/comment/entity/Comment.java
  src/main/java/kr/sparta/rchive/domain/comment/repository/CommentRepository.java
  src/main/java/kr/sparta/rchive/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/comment/repository/CommentRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/comment/service/CommentService.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostCommentCoreService.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetSinglePostRes.java
  src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
  src/main/java/kr/sparta/rchive/domain/post/exception/PostExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/post/repository/TutorRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
Labels: enhancement

#225 [#222] BackOffice : 프론트 개발 중 수정사항 발생 수정 완료
  src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
Labels: refactor

#227 [#226] Comment: 댓글의 대댓글 조회하는 기능 추가
  src/main/java/kr/sparta/rchive/domain/comment/repository/CommentRepository.java
  src/main/java/kr/sparta/rchive/domain/comment/service/CommentService.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostCommentCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
Labels: enhancement

#220 [#202] CICD: cicd 테스트
  .github/workflows/ci-dev.yml
  .github/workflows/ci-prod.yml
  .github/workflows/ci.yml
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
  Dockerfile
  src/main/java/kr/sparta/rchive/global/config/SwaggerConfig.java
  src/main/java/kr/sparta/rchive/global/config/WebMvcConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
Labels: enhancement

#242 [#202] CICD: CORS 에러
  src/main/java/kr/sparta/rchive/global/config/WebMvcConfig.java
Labels: fix

#243 [#241] Post: 검색기능 관련 수정
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetSinglePostRes.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
Labels: fix

#251 [#246] Track: TrackNameEnum 변경
  src/main/java/kr/sparta/rchive/domain/user/enums/TrackNameEnum.java
Labels: enhancement

#250 [#249] 유저의 최근 검색 기록 가져오는 기능 추가
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetRecentKeywordRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchBackOfficeRes.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
  src/main/java/kr/sparta/rchive/global/redis/RedisService.java
  src/main/java/kr/sparta/rchive/global/redis/RedisUtil.java
Labels: enhancement

#248 [#247] 게시물 열람 권한 기능 수정
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetRecentKeywordRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchBackOfficeRes.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/main/java/kr/sparta/rchive/global/config/WebMvcConfig.java
  src/main/java/kr/sparta/rchive/global/redis/RedisService.java
  src/main/java/kr/sparta/rchive/global/redis/RedisUtil.java
Labels: fix

#245 [#244] Post: 최근 검색한 기록 저장하는 기능 추가
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/RecentSearchKeywordReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetRecentKeywordRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchBackOfficeRes.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/main/java/kr/sparta/rchive/global/config/WebSecurityConfig.java
  src/main/java/kr/sparta/rchive/global/redis/RedisService.java
  src/main/java/kr/sparta/rchive/global/redis/RedisUtil.java
Labels: enhancement

#254 [#202] CICD: cicd 수정
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
Labels: enhancement

#255 [#202] CICD: cicd 수정
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
Labels: enhancement

#257 [#256] API: URL 수정
  src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchRes.java
  src/main/java/kr/sparta/rchive/domain/user/controller/ProfileController.java
  src/main/java/kr/sparta/rchive/domain/user/controller/RoleController.java
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
  src/main/java/kr/sparta/rchive/global/config/WebSecurityConfig.java
  src/main/java/kr/sparta/rchive/global/s3/controller/S3ImageController.java
Labels: fix

#260 [#259] API: url 수정
  src/main/java/kr/sparta/rchive/global/config/SwaggerConfig.java
  src/main/java/kr/sparta/rchive/global/execption/ExceptionController.java
  src/main/java/kr/sparta/rchive/global/security/LoginFilter.java
Labels: refactor

#261 [#253] Rchive: dev to main
  src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchRes.java
  src/main/java/kr/sparta/rchive/domain/user/controller/ProfileController.java
  src/main/java/kr/sparta/rchive/domain/user/controller/RoleController.java
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
  src/main/java/kr/sparta/rchive/global/config/SwaggerConfig.java
  src/main/java/kr/sparta/rchive/global/config/WebSecurityConfig.java
  src/main/java/kr/sparta/rchive/global/execption/ExceptionController.java
  src/main/java/kr/sparta/rchive/global/s3/controller/S3ImageController.java
  src/main/java/kr/sparta/rchive/global/security/LoginFilter.java
Labels: release

#262 [#165] HOTFIX: 리프레시토큰 set-cookie 오류
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
  src/main/java/kr/sparta/rchive/global/security/JwtUtil.java
  src/main/java/kr/sparta/rchive/global/security/LoginFilter.java
Labels: fix

#264 [#263] Post: 게시물의 수준별 교육자료 전체를 조회할 수 있는 로직 추가
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/enums/PostTypeEnum.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
Labels: enhancement

#270 [#269] JWT: 프론트 로그인 테스트를 위한 accessToken과 refreshToken 시간 변경
  src/main/java/kr/sparta/rchive/global/security/JwtUtil.java
Labels: fix

#272 [#271] Security: reissue 권한 변경
  src/main/java/kr/sparta/rchive/global/config/WebSecurityConfig.java
Labels: fix

#276 [#275] Token: 프론트 요청으로 Refresh Token 시간 변견
  src/main/java/kr/sparta/rchive/global/security/JwtUtil.java
Labels: fix

#278 [#277] User: Access Token 만료 여부 조회하는 api 추가
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
  src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
  src/main/java/kr/sparta/rchive/global/security/JwtAuthorizationFilter.java
Labels: enhancement

#274 [#273] Swagger: 추가 API로 인해 추가 된 예외 명세서 정리
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/exception/statement/DeleteRecentSearchKeywordException.java
  src/main/java/kr/sparta/rchive/domain/post/exception/statement/GetRecentSearchKeywordException.java
  src/main/java/kr/sparta/rchive/domain/post/exception/statement/SaveRecentSearchKeywordException.java
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
  src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
  src/main/java/kr/sparta/rchive/global/security/JwtAuthorizationFilter.java
Labels: documentation

#268 [#267] Profile: 자신이 북마크한 게시물들 검색할 수 있는 기능 추가
  src/main/java/kr/sparta/rchive/domain/bookmark/repository/BookmarkRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/bookmark/repository/BookmarkRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/bookmark/service/BookmarkService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostRes.java
  src/main/java/kr/sparta/rchive/domain/post/exception/statement/DeleteRecentSearchKeywordException.java
  src/main/java/kr/sparta/rchive/domain/post/exception/statement/GetRecentSearchKeywordException.java
  src/main/java/kr/sparta/rchive/domain/post/exception/statement/SaveRecentSearchKeywordException.java
  src/main/java/kr/sparta/rchive/domain/user/controller/ProfileController.java
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
  src/main/java/kr/sparta/rchive/domain/user/response/ProfileResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
  src/main/java/kr/sparta/rchive/global/security/JwtAuthorizationFilter.java
Labels: enhancement

#266 [#265] 최근 검색한 기록 삭제하는 기능 추가
  src/main/java/kr/sparta/rchive/domain/bookmark/repository/BookmarkRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/bookmark/repository/BookmarkRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/bookmark/service/BookmarkService.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostRes.java
  src/main/java/kr/sparta/rchive/domain/post/exception/statement/DeleteRecentSearchKeywordException.java
  src/main/java/kr/sparta/rchive/domain/post/exception/statement/GetRecentSearchKeywordException.java
  src/main/java/kr/sparta/rchive/domain/post/exception/statement/SaveRecentSearchKeywordException.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/controller/ProfileController.java
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
  src/main/java/kr/sparta/rchive/domain/user/response/ProfileResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
  src/main/java/kr/sparta/rchive/global/redis/RedisService.java
  src/main/java/kr/sparta/rchive/global/redis/RedisUtil.java
  src/main/java/kr/sparta/rchive/global/security/JwtAuthorizationFilter.java
Labels: enhancement

#280 [#279] Token: Access Token 시간 변경
  src/main/java/kr/sparta/rchive/global/security/JwtUtil.java
Labels: fix

#282 [#281] Role: APM이 권한 신청한 인원 카운트하는 로직 수정
  src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepositoryCustomImpl.java
Labels: fix

#284 [#283] test: 프엔과 로그인 테스트
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
Labels: test

#286 [#283] test: 프론트와 로그인 테스트
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
Labels: test

#287 [#285] BackOffice: 백오피스 권한 요청 조회 기능 수정
  src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
Labels: refactor

#289 [#283] test: 로그인 테스트
  src/main/java/kr/sparta/rchive/global/security/JwtUtil.java
Labels: test

#292 [#288] User: 휴대폰 인증 전송
  .github/workflows/ci-dev.yml
  .github/workflows/ci-prod.yml
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/AuthPhoneReq.java
  src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
  src/main/java/kr/sparta/rchive/global/config/RestTemplateConfig.java
  src/main/java/kr/sparta/rchive/global/redis/RedisService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
Labels: enhancement

#291 [#290] BackOffice: 백오피스에서 게시물 수정 시 기존 게시물 내용 조회하는 기능 추가
  src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
  src/main/java/kr/sparta/rchive/domain/backoffice/respoonse/BackofficeResponseCode.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostModifyPreviewRes.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
Labels: enhancement

#300 [#295] User: 이메일 찾기
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/FindEmailReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/response/FindEmailRes.java
  src/main/java/kr/sparta/rchive/domain/user/exception/UserExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/user/repository/UserRepository.java
  src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
Labels: enhancement

#301 [#296] User: 비밀번호 찾기
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/FindPasswordReq.java
  src/main/java/kr/sparta/rchive/domain/user/repository/UserRepository.java
  src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
Labels: enhancement

#304 [#297] User: 비밀번호 찾기 후 변경
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindEmailReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindPasswordReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindPasswordUpdateReq.java
  src/main/java/kr/sparta/rchive/domain/user/repository/UserRepository.java
  src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
Labels: enhancement

#302 [#298] User: 이메일 비밀번호 찾기
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindEmailReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindPasswordReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindPasswordUpdateReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/response/FindEmailRes.java
  src/main/java/kr/sparta/rchive/domain/user/exception/UserExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/user/repository/UserRepository.java
  src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
Labels: enhancement

#303 [#299] Test: 테스트를 위한 환경 구축 및 게시물 생성 기능 성공 테스트 작성
  build.gradle
  src/main/java/kr/sparta/rchive/RchiveApplication.java
  src/main/java/kr/sparta/rchive/global/config/AuditingConfig.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForPM.java
  src/test/java/kr/sparta/rchive/security/WithMockCustomPM.java
  src/test/java/kr/sparta/rchive/security/WithMockCustomPMSecurityContextFactory.java
  src/test/java/kr/sparta/rchive/test/UserTest.java
  src/test/resources/application-test.yml
Labels: test

#307 [#305] refactor(Role): 기존 apm이 새로운 트랙의 apm으로 변경될 시, 기존의 권한 삭제
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepository.java
  src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
Labels: refactor

#309 [#306] Profile: 자신이 작성한 댓글 프로필에서 조회하는 기능 추가
  src/main/java/kr/sparta/rchive/domain/comment/dto/response/CommentProfileRes.java
  src/main/java/kr/sparta/rchive/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/comment/repository/CommentRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/comment/service/CommentService.java
  src/main/java/kr/sparta/rchive/domain/user/controller/ProfileController.java
  src/main/java/kr/sparta/rchive/domain/user/response/ProfileResponseCode.java
Labels: enhancement

#310 [#308] User: 비밀번호 찾기 수정
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindPasswordCheckEmailReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindPasswordCheckPhoneReq.java
  src/main/java/kr/sparta/rchive/domain/user/repository/UserRepository.java
  src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
Labels: enhancement

#314 [#313] BackOffice: 백오피스 권한 관련 수정
  src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
Labels: enhancement

#316 [#315] CICD: 성능개선
  .github/workflows/ci-dev.yml
  .github/workflows/ci-prod.yml
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
Labels: refactor

#318 [#315] CICD: 성능개선
  .github/workflows/ci-prod.yml
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
Labels: refactor

#319 [#315] CICD: 성능개선
  .github/workflows/ci-dev.yml
  .github/workflows/ci-prod.yml
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
Labels: refactor

#321 [#315] CICD: 성능 개선
  .github/workflows/cicd-dev.yml
Labels: refactor

#322 [#315] CICD: 성능 개선
  .github/workflows/cicd-dev.yml
Labels: refactor

#325 [#324] Refactor: 로직 수정
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/domain/user/controller/ProfileController.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdateNicknameReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdatePasswordReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdateProfileImgReq.java
  src/main/java/kr/sparta/rchive/domain/user/entity/User.java
  src/main/java/kr/sparta/rchive/domain/user/exception/UserExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/user/response/ProfileResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
Labels: refactor

#326 [#324] Refactor: 로직 수정
  src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdateNicknameReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserSignupReq.java
  src/main/java/kr/sparta/rchive/domain/user/entity/User.java
  src/main/java/kr/sparta/rchive/domain/user/exception/UserExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
Labels: refactor

#317 [#312] Test: PM과 관련된 PostController 테스트 코드 작성
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/PostOpenCloseReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/PostUpdateReq.java
  src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForPM.java
Labels: test

#327 [#324] Refactor: 로직 수정
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/domain/user/exception/UserExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepository.java
  src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
Labels: enhancement

#330 [#311] Test: PostController 테스트 코드 작성
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/PostOpenCloseReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/PostUpdateReq.java
  src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForPM.java
  src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForUser.java
  src/test/java/kr/sparta/rchive/security/WithMockCustomUser.java
  src/test/java/kr/sparta/rchive/security/WithMockCustomUserSecurityContextFactory.java
  src/test/java/kr/sparta/rchive/test/CommentTest.java
  src/test/java/kr/sparta/rchive/test/PostTest.java
  src/test/java/kr/sparta/rchive/test/TagTest.java
  src/test/java/kr/sparta/rchive/test/TrackTest.java
  src/test/java/kr/sparta/rchive/test/TutorTest.java
Labels: test

#332 [#331] CORS: 서브도메인 수정
  src/main/java/kr/sparta/rchive/global/config/WebMvcConfig.java
Labels: enhancement

#334 [#333] test: 프론트엔드 테스트
  src/main/java/kr/sparta/rchive/global/security/JwtUtil.java
Labels: test

#335 [#333] User: signup 수정
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserSignupReq.java
  src/main/java/kr/sparta/rchive/domain/user/entity/User.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
Labels: refactor

#336 [#333] Test: 로그인 테스트
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
Labels: test

#337 [#333] Test: 로그인 테스트
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
Labels: enhancement

#339 [#338] BackOffice: 백오피스 게시물 검색 시 삭제된 게시물 보이지 않도록 변경
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
Labels: fix

#343 [#253] Rchive: release ver1.0
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/PostOpenCloseReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/PostUpdateReq.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/user/controller/ProfileController.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdateNicknameReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdatePasswordReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdateProfileImgReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserSignupReq.java
  src/main/java/kr/sparta/rchive/domain/user/entity/User.java
  src/main/java/kr/sparta/rchive/domain/user/exception/UserExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepository.java
  src/main/java/kr/sparta/rchive/domain/user/response/ProfileResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
  src/main/java/kr/sparta/rchive/global/config/WebMvcConfig.java
  src/main/java/kr/sparta/rchive/global/security/JwtUtil.java
  src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForPM.java
  src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForUser.java
  src/test/java/kr/sparta/rchive/security/WithMockCustomUser.java
  src/test/java/kr/sparta/rchive/security/WithMockCustomUserSecurityContextFactory.java
  src/test/java/kr/sparta/rchive/test/CommentTest.java
  src/test/java/kr/sparta/rchive/test/PostTest.java
  src/test/java/kr/sparta/rchive/test/TagTest.java
  src/test/java/kr/sparta/rchive/test/TrackTest.java
  src/test/java/kr/sparta/rchive/test/TutorTest.java
Labels: release
