Repository sparta-incubating/rchive-back, pull requests merged in 2024-07, with the labels that each got.

#34 [#25] feat(Tag): 태그를 이용하여 게시물 검색하는 기능 추가
  src/main/java/kr/sparta/rchive/domain/core/service/EducationDataTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchByTagRes.java
  src/main/java/kr/sparta/rchive/domain/post/entity/EducationDataTag.java
  src/main/java/kr/sparta/rchive/domain/post/entity/EducationDataTrack.java
  src/main/java/kr/sparta/rchive/domain/post/exception/PostExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/post/repository/EducationDataTagRepository.java
  src/main/java/kr/sparta/rchive/domain/post/repository/EducationDataTrackRepository.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
  src/main/java/kr/sparta/rchive/domain/post/service/EducationDataService.java
  src/main/java/kr/sparta/rchive/domain/post/service/EducationDataTagService.java
  src/main/java/kr/sparta/rchive/domain/post/service/EducationDataTrackService.java
  src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
  src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepository.java
  src/main/java/kr/sparta/rchive/domain/user/repository/TrackRepository.java
  src/main/java/kr/sparta/rchive/domain/user/repository/UserRepository.java
  src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
  src/main/java/kr/sparta/rchive/domain/user/service/TrackService.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
Labels: enhancement

#36 [#35] feat(Redis): Redis를 사용하기 위한 의존성 추가 및 임시 config / util 추가
  .github/workflows/ci.yml
  build.gradle
  src/main/java/kr/sparta/rchive/global/redis/RedisConfig.java
  src/main/java/kr/sparta/rchive/global/redis/RedisUtil.java
  src/main/resources/application.yml
Labels: enhancement

#39 회원가입 로그인 구현
  .github/workflows/ci.yml
  build.gradle
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserSignupReq.java
  src/main/java/kr/sparta/rchive/domain/user/entity/Track.java
  src/main/java/kr/sparta/rchive/domain/user/entity/User.java
  src/main/java/kr/sparta/rchive/domain/user/enums/OAuthTypeEnum.java
  src/main/java/kr/sparta/rchive/domain/user/enums/UserRoleEnum.java
  src/main/java/kr/sparta/rchive/domain/user/repository/UserRepository.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
  src/main/java/kr/sparta/rchive/global/config/SwaggerConfig.java
  src/main/java/kr/sparta/rchive/global/config/WebSecurityConfig.java
  src/main/java/kr/sparta/rchive/global/security/JwtAuthorizationFilter.java
  src/main/java/kr/sparta/rchive/global/security/JwtUtil.java
  src/main/java/kr/sparta/rchive/global/security/LoginFilter.java
  src/main/java/kr/sparta/rchive/global/security/UserDetailsImpl.java
  src/main/java/kr/sparta/rchive/global/security/UserDetailsServiceImpl.java
  src/main/resources/application.yml
Labels: enhancement

#41 회원가입 PR 리뷰 적용
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserLoginReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserSignupReq.java
  src/main/java/kr/sparta/rchive/domain/user/entity/User.java
  src/main/java/kr/sparta/rchive/domain/user/exception/UserExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
  src/main/java/kr/sparta/rchive/global/config/WebSecurityConfig.java
  src/main/java/kr/sparta/rchive/global/security/JwtAuthorizationFilter.java
  src/main/java/kr/sparta/rchive/global/security/JwtUtil.java
  src/main/java/kr/sparta/rchive/global/security/LoginFilter.java
  src/main/java/kr/sparta/rchive/global/security/UserDetailsImpl.java
  src/main/java/kr/sparta/rchive/global/security/UserDetailsServiceImpl.java
  src/main/resources/application.yml
Labels: enhancement

#38 [#37] feat(Paging): 페이징 기능 추가 및 커스텀 페이징 클래스 추가
  src/main/java/kr/sparta/rchive/domain/bookmark/entity/Bookmark.java
  src/main/java/kr/sparta/rchive/domain/bookmark/entity/BookmarkId.java
  src/main/java/kr/sparta/rchive/domain/comment/entity/Comment.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/PostCreateReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostCreateRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchRes.java
  src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
  src/main/java/kr/sparta/rchive/domain/post/entity/PostTag.java
  src/main/java/kr/sparta/rchive/domain/post/entity/PostTagId.java
  src/main/java/kr/sparta/rchive/domain/post/entity/PostTrack.java
  src/main/java/kr/sparta/rchive/domain/post/entity/PostTrackId.java
  src/main/java/kr/sparta/rchive/domain/post/enums/PostTypeEnum.java
  src/main/java/kr/sparta/rchive/domain/post/exception/PostExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/post/repository/EducationDataRepository.java
  src/main/java/kr/sparta/rchive/domain/post/repository/EducationDataTagRepository.java
  src/main/java/kr/sparta/rchive/domain/post/repository/EducationDataTrackRepository.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepository.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostTagRepository.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostTrackRepository.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
  src/main/java/kr/sparta/rchive/domain/post/service/EducationDataTagService.java
  src/main/java/kr/sparta/rchive/domain/post/service/EducationDataTrackService.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostTagService.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostTrackService.java
  src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
  src/main/java/kr/sparta/rchive/domain/user/entity/Track.java
  src/main/java/kr/sparta/rchive/global/config/WebSecurityConfig.java
  src/main/java/kr/sparta/rchive/global/custom/CustomPageable.java
  src/main/java/kr/sparta/rchive/global/redis/RedisService.java
  src/main/java/kr/sparta/rchive/global/redis/RedisUtil.java
  src/main/java/kr/sparta/rchive/global/security/LoginFilter.java
Labels: enhancement

#44 [#43] Post 생성 기능 추가
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/PostCreateReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostCreateRes.java
  src/main/java/kr/sparta/rchive/domain/post/entity/Content.java
  src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
  src/main/java/kr/sparta/rchive/domain/post/repository/ContentRepository.java
  src/main/java/kr/sparta/rchive/domain/post/repository/TagRepository.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
  src/main/java/kr/sparta/rchive/domain/post/service/ContentService.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostTagService.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostTrackService.java
  src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
  src/main/java/kr/sparta/rchive/domain/user/entity/Track.java
  src/main/java/kr/sparta/rchive/domain/user/repository/TrackRepository.java
  src/main/java/kr/sparta/rchive/domain/user/service/TrackService.java
  src/main/java/kr/sparta/rchive/global/config/WebSecurityConfig.java
  src/main/java/kr/sparta/rchive/global/redis/RedisService.java
Labels: enhancement

#45 [#42] User: 리프레시 토큰 관련 구현
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
  src/main/java/kr/sparta/rchive/domain/user/entity/User.java
  src/main/java/kr/sparta/rchive/domain/user/exception/UserExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/user/repository/UserRepository.java
  src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
  src/main/java/kr/sparta/rchive/global/config/WebSecurityConfig.java
  src/main/java/kr/sparta/rchive/global/execption/GlobalCustomException.java
  src/main/java/kr/sparta/rchive/global/execption/GlobalExceptionCode.java
  src/main/java/kr/sparta/rchive/global/execption/GlobalExceptionHandler.java
  src/main/java/kr/sparta/rchive/global/redis/RedisService.java
  src/main/java/kr/sparta/rchive/global/security/JwtAuthorizationFilter.java
  src/main/java/kr/sparta/rchive/global/security/JwtUtil.java
  src/main/java/kr/sparta/rchive/global/security/LoginFilter.java
  src/main/java/kr/sparta/rchive/global/security/UserDetailsServiceImpl.java
Labels: enhancement

#47 [#46] User: 로그아웃
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
  src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
  src/main/java/kr/sparta/rchive/global/redis/RedisService.java
Labels: enhancement

#49 [#48] User: 회원탈퇴
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
  src/main/java/kr/sparta/rchive/domain/user/entity/User.java
  src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
  src/main/java/kr/sparta/rchive/global/security/JwtUtil.java
Labels: enhancement

#55 [#53] User: 이메일 중복 여부 조회 구현
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
  src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
Labels: enhancement

#56 [#54] User: 닉네임 중복 여부 조회 구현
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
  src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
Labels: enhancement

#61 [#57] Role: 내 권한(트랙 및 기수) 요청
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/PostCreateReq.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostTrackService.java
  src/main/java/kr/sparta/rchive/domain/user/controller/RoleController.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/RoleRequestReq.java
  src/main/java/kr/sparta/rchive/domain/user/entity/Track.java
  src/main/java/kr/sparta/rchive/domain/user/enums/TrackNameEnum.java
  src/main/java/kr/sparta/rchive/domain/user/repository/TrackRepository.java
  src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
  src/main/java/kr/sparta/rchive/domain/user/service/TrackService.java
  src/main/java/kr/sparta/rchive/global/config/WebSecurityConfig.java
Labels: enhancement

#68 [#67] User: 회원가입 수정
  src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
  src/main/java/kr/sparta/rchive/domain/user/entity/Track.java
  src/main/java/kr/sparta/rchive/domain/user/entity/User.java
  src/main/java/kr/sparta/rchive/global/security/JwtUtil.java
Labels: enhancement

#51 [#50] Post: 게시물 관리 삭제 기능 추가
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
  src/main/java/kr/sparta/rchive/domain/post/entity/Tag.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/main/java/kr/sparta/rchive/domain/user/entity/Track.java
Labels: enhancement

#71 [#69] User: 회원가입 로그인 수정
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserSignupReq.java
  src/main/java/kr/sparta/rchive/domain/user/entity/User.java
  src/main/java/kr/sparta/rchive/domain/user/exception/UserExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
Labels: enhancement

#74 [#73] User: 이메일 중복, 닉네임 중복 수정
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
Labels: enhancement

#75 [#62] Role: 트랙명 조회
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/domain/user/controller/RoleController.java
  src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleGetTrackNameListReq.java
  src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/TrackService.java
Labels: enhancement

#78 [#63] Role: 트랙의 기수 조회
  src/main/java/kr/sparta/rchive/domain/user/controller/RoleController.java
  src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleGetTrackNameListRes.java
  src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleGetTrackPeriodListRes.java
  src/main/java/kr/sparta/rchive/domain/user/repository/TrackRepository.java
  src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/TrackService.java
Labels: enhancement

#80 [#72] CORS 설정
  src/main/java/kr/sparta/rchive/global/config/WebMvcConfig.java
Labels: enhancement

#81 [#79] Role: 권한 신청 여부 조회 - 최초 로그인
  src/main/java/kr/sparta/rchive/domain/user/controller/RoleController.java
  src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepository.java
  src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
  src/main/java/kr/sparta/rchive/domain/user/service/TrackService.java
Labels: enhancement

#86 [#85] Role: 마지막에 선택한 권한 조회 - 백오피스
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/domain/user/controller/RoleController.java
  src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleGetLastSelectRoleRes.java
  src/main/java/kr/sparta/rchive/domain/user/exception/RoleExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepository.java
  src/main/java/kr/sparta/rchive/domain/user/response/RoleResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
  src/main/java/kr/sparta/rchive/global/config/WebSecurityConfig.java
Labels: enhancement

#91 [#90] User: username 추가
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserSignupReq.java
  src/main/java/kr/sparta/rchive/domain/user/entity/User.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
Labels: enhancement

#92 [#83, #77] 카테고리 별 게시글 목록 조회 기능 추가 / 게시글 단건 조회 기능 추가
  src/main/java/kr/sparta/rchive/domain/comment/dto/response/CommentRes.java
  src/main/java/kr/sparta/rchive/domain/comment/repository/CommentRepository.java
  src/main/java/kr/sparta/rchive/domain/comment/service/CommentService.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetCategoryPostRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetSinglePostRes.java
  src/main/java/kr/sparta/rchive/domain/post/entity/Tag.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepository.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostTagRepository.java
  src/main/java/kr/sparta/rchive/domain/post/repository/TagRepository.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
  src/main/java/kr/sparta/rchive/domain/post/service/ContentService.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostTagService.java
  src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
  src/main/java/kr/sparta/rchive/domain/user/exception/RoleExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepository.java
  src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
Labels: enhancement

#98 [#97] Post: 게시물 공개 여부 상태 공개로 변경하는 로직 추가
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
Labels: enhancement

#100 [#89] Profile: 비밀번호 변경
  src/main/java/kr/sparta/rchive/domain/user/controller/ProfileController.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdatePasswordReq.java
  src/main/java/kr/sparta/rchive/domain/user/entity/User.java
  src/main/java/kr/sparta/rchive/domain/user/exception/UserExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/user/response/ProfileResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
Labels: enhancement

#101 [#99] Post: 게시물 공개 여부 상태 비공개로 변경하는 로직 추가
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
Labels: enhancement

#104 [#102] BackOffice: 유저의 트랙 권한 수락
  src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
  src/main/java/kr/sparta/rchive/domain/backoffice/respoonse/BackofficeResponseCode.java
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/RoleRequestListReq.java
  src/main/java/kr/sparta/rchive/domain/user/entity/Role.java
  src/main/java/kr/sparta/rchive/domain/user/exception/RoleExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepository.java
  src/main/java/kr/sparta/rchive/domain/user/repository/UserRepository.java
  src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
Labels: enhancement

#105 [#103] BackOffice: 유저의 트랙 권한 거절
  src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
  src/main/java/kr/sparta/rchive/domain/backoffice/respoonse/BackofficeResponseCode.java
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/domain/user/entity/Role.java
  src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
Labels: enhancement

#107 [#106] BackOffice: 유저의 트랙 권한 수락 - auth approve 제외하고 삭제
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepository.java
  src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
Labels: enhancement

#116 [#115] User: 프로필이미지 추가
  src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserSignupReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/response/UserRes.java
  src/main/java/kr/sparta/rchive/domain/user/entity/User.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
Labels: enhancement

#117 [#88] Profile: 프로필 수정
  src/main/java/kr/sparta/rchive/domain/user/controller/ProfileController.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdateReq.java
  src/main/java/kr/sparta/rchive/domain/user/entity/User.java
  src/main/java/kr/sparta/rchive/domain/user/response/ProfileResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
Labels: enhancement

#119 [#113] 백오피스: 백오피스에서의 게시물 조회 기능 수정
  src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/TagInfo.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchBackOfficeRes.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepository.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
Labels: refactor

#120 [#110] Post: 카테고리로 게시물 목록 조회하는 기능 수정
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/PostSearchInfo.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetCategoryPostRes.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepository.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
Labels: refactor

#122 [#111] Post: 게시물 단건 조회 성능 개선 및 리팩토링
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetSinglePostRes.java
  src/main/java/kr/sparta/rchive/domain/post/entity/Content.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepository.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/post/service/ContentService.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
Labels: refactor

#123 [#118] BackOffice: 유저의 트랙 권한 신청 건수
  src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
  src/main/java/kr/sparta/rchive/domain/backoffice/respoonse/BackofficeResponseCode.java
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleGetTrackRoleRequestCountRes.java
  src/main/java/kr/sparta/rchive/domain/user/exception/RoleExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepository.java
  src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
Labels: enhancement

#127 [#121] User: 유저 밸리데이션
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserSignupReq.java
  src/main/java/kr/sparta/rchive/domain/user/entity/User.java
Labels: enhancement

#136 [#130] S3: 썸네일 업로드 기능 추가
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/PostCreateReq.java
  src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/main/java/kr/sparta/rchive/global/config/WebSecurityConfig.java
  src/main/java/kr/sparta/rchive/global/execption/GlobalExceptionCode.java
  src/main/java/kr/sparta/rchive/global/response/GlobalResponseCode.java
  src/main/java/kr/sparta/rchive/global/s3/S3ImageController.java
  src/main/java/kr/sparta/rchive/global/s3/S3ImageService.java
Labels: enhancement

#140 [#133] BackOffice: 유저의 트랙 권한 신청 목록 조회
  src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
  src/main/java/kr/sparta/rchive/domain/backoffice/respoonse/BackofficeResponseCode.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleGetTrackRoleRequestListRes.java
  src/main/java/kr/sparta/rchive/domain/user/exception/RoleExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepository.java
  src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
Labels: enhancement

#142 [#132] 게시물 검색 시 썸네일이 보이는 기능 추가
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetCategoryPostRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchBackOfficeRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchByTagRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchRes.java
Labels: enhancement

#141 [#139] 게시물 조회 및 수정 삭제 권한 로직 수정
  src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/PostCreateReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/PostModifyReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetCategoryPostRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchBackOfficeRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchByTagRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchRes.java
  src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
  src/main/java/kr/sparta/rchive/domain/post/exception/PostExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
Labels: fix

#144 [#129] S3: 썸네일 관련 기능 추가 및
  src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/PostTrackInfo.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/PostCreateReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/PostModifyReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetCategoryPostRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchBackOfficeRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchByTagRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchRes.java
  src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
  src/main/java/kr/sparta/rchive/domain/post/exception/PostExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/main/java/kr/sparta/rchive/global/config/WebSecurityConfig.java
  src/main/java/kr/sparta/rchive/global/execption/GlobalExceptionCode.java
  src/main/java/kr/sparta/rchive/global/response/GlobalResponseCode.java
  src/main/java/kr/sparta/rchive/global/s3/S3ImageController.java
  src/main/java/kr/sparta/rchive/global/s3/S3ImageService.java
Labels: enhancement

#145 [#143] Role: 내 권한(트랙 및 기수) 조회
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/domain/user/controller/RoleController.java
  src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleRes.java
  src/main/java/kr/sparta/rchive/domain/user/repository/TrackRepository.java
  src/main/java/kr/sparta/rchive/domain/user/response/RoleResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
  src/main/java/kr/sparta/rchive/domain/user/service/TrackService.java
Labels: enhancement

#148 [#147] Bookmark: 북마크 추가하고 삭제하는 기능 추가
  src/main/java/kr/sparta/rchive/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/kr/sparta/rchive/domain/bookmark/service/BookmarkService.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostBookmarkCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/exception/PostExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
Labels: enhancement

#150 [#149] CI: CI 속도향상
  .github/workflows/ci.yml
Labels: enhancement

#154 [#153] refactor: exception, response 코드 맞추기
  src/main/java/kr/sparta/rchive/domain/bookmark/service/BookmarkService.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/exception/PostExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
  src/main/java/kr/sparta/rchive/domain/user/controller/ProfileController.java
  src/main/java/kr/sparta/rchive/domain/user/controller/RoleController.java
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
  src/main/java/kr/sparta/rchive/domain/user/exception/RoleExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/user/exception/TrackCustomException.java
  src/main/java/kr/sparta/rchive/domain/user/exception/TrackExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/user/exception/UserExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/user/response/ProfileResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/response/RoleResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/response/UserResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/TrackService.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
  src/main/java/kr/sparta/rchive/global/execption/GlobalExceptionCode.java
  src/main/java/kr/sparta/rchive/global/response/GlobalResponseCode.java
  src/main/java/kr/sparta/rchive/global/s3/S3ImageController.java
Labels: enhancement

#151 [#146] Role: 내 권한(트랙 및 기수) 선택
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/domain/user/controller/RoleController.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/RoleSelectRoleReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleRes.java
  src/main/java/kr/sparta/rchive/domain/user/response/RoleResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
  src/main/java/kr/sparta/rchive/global/redis/RedisConfig.java
  src/main/java/kr/sparta/rchive/global/redis/RedisService.java
  src/main/java/kr/sparta/rchive/global/redis/RedisUtil.java
Labels: enhancement

#155 [#152] Role: 마지막 선택한 권한 조회 - 유저페이지
  src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/domain/user/controller/RoleController.java
  src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleGetLastSelectRoleRes.java
  src/main/java/kr/sparta/rchive/domain/user/exception/RoleExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/user/response/RoleResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
  src/main/java/kr/sparta/rchive/global/redis/RedisService.java
Labels: enhancement

#157 [#156] 에러 코드 수정
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/domain/user/exception/RoleExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
Labels: enhancement

#160 [#158] S3: 파일 업로드 용량 변경 및 예외 처리
  src/main/java/kr/sparta/rchive/domain/bookmark/service/BookmarkService.java
  src/main/java/kr/sparta/rchive/domain/post/exception/PostCustomException.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
  src/main/java/kr/sparta/rchive/global/config/S3Config.java
  src/main/java/kr/sparta/rchive/global/execption/GlobalExceptionCode.java
  src/main/java/kr/sparta/rchive/global/execption/GlobalExceptionHandler.java
  src/main/java/kr/sparta/rchive/global/response/GlobalResponseCode.java
  src/main/java/kr/sparta/rchive/global/s3/controller/S3ImageController.java
  src/main/java/kr/sparta/rchive/global/s3/exception/S3CustomException.java
  src/main/java/kr/sparta/rchive/global/s3/exception/S3ExceptionCode.java
  src/main/java/kr/sparta/rchive/global/s3/response/S3ResponseCode.java
  src/main/java/kr/sparta/rchive/global/s3/service/S3ImageService.java
  src/main/resources/application.yml
Labels: fix

#168 [#166] fix(Post): 게시물과 트랙이 일치하는지 체크하는 로직 추가
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
  src/main/java/kr/sparta/rchive/domain/user/exception/TrackExceptionCode.java
Labels: fix

#162 [#159] Swagger: 에러 리스트 작성
  src/main/java/kr/sparta/rchive/domain/post/exception/PostExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
  src/main/java/kr/sparta/rchive/domain/user/exception/RoleExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/user/exception/TrackExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/user/exception/UserExceptionCode.java
  src/main/java/kr/sparta/rchive/global/config/SwaggerConfig.java
  src/main/java/kr/sparta/rchive/global/config/SwaggerExampleHolder.java
  src/main/java/kr/sparta/rchive/global/execption/ApiExceptionCodeExample.java
  src/main/java/kr/sparta/rchive/global/execption/ExceptionCode.java
  src/main/java/kr/sparta/rchive/global/execption/ExceptionController.java
  src/main/java/kr/sparta/rchive/global/execption/ExceptionReason.java
  src/main/java/kr/sparta/rchive/global/execption/ExceptionResponse.java
  src/main/java/kr/sparta/rchive/global/execption/ExplainException.java
  src/main/java/kr/sparta/rchive/global/execption/GlobalExceptionCode.java
Labels: enhancement

#169 [#163] Profile: 내 프로필 조회
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/domain/user/controller/ProfileController.java
  src/main/java/kr/sparta/rchive/domain/user/controller/RoleController.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/RoleReq.java
  src/main/java/kr/sparta/rchive/domain/user/exception/RoleExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/user/response/ProfileResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
Labels: enhancement

#170 [#164] Profile: 휴대폰 번호 변경
  src/main/java/kr/sparta/rchive/domain/user/controller/ProfileController.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdatePhoneReq.java
  src/main/java/kr/sparta/rchive/domain/user/entity/User.java
  src/main/java/kr/sparta/rchive/domain/user/response/ProfileResponseCode.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
Labels: enhancement

#172 [#171] BackOffice: 권한 신청 목록 조회 - 정렬
  src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/domain/user/enums/OrderRoleListEnum.java
  src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
Labels: enhancement

#175 [#173] Swagger: 에러 문서화
  src/main/java/kr/sparta/rchive/global/config/SwaggerConfig.java
  src/main/java/kr/sparta/rchive/global/execption/ExceptionResponse.java
Labels: enhancement

#183 [#182] Tutor: 튜터 추가로 인한 백오피스 게시물 관련 수정
  src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
Labels: refactor

#181 [#180] Tutor: 튜터를 검색해오는 기능 추가
  src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/controller/TutorRes.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/post/repository/TutorRepository.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/main/java/kr/sparta/rchive/domain/post/service/TutorService.java
Labels: enhancement

#179 [#178] Tutor: 유저가 게시물 조회할 때 변경되는 사항 적용
  src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/controller/TutorRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetSinglePostRes.java
  src/main/java/kr/sparta/rchive/domain/post/entity/Tutor.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/post/repository/TutorRepository.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/main/java/kr/sparta/rchive/domain/post/service/TutorService.java
Labels: enhancement

#177 [#176] Tutor: 게시물 수정 관련 튜터 추가
  src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/controller/TutorRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/PostCreateReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/PostUpdateReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetSinglePostRes.java
  src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
  src/main/java/kr/sparta/rchive/domain/post/entity/Tutor.java
  src/main/java/kr/sparta/rchive/domain/post/exception/PostExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/post/repository/TutorRepository.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/main/java/kr/sparta/rchive/domain/post/service/TutorService.java
Labels: enhancement

#174 [#167] Tutor: 튜터 추가로 인한 게시글 생성 시 로직 변경
  src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/controller/TutorRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/PostCreateReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/PostUpdateReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetSinglePostRes.java
  src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
  src/main/java/kr/sparta/rchive/domain/post/entity/Tutor.java
  src/main/java/kr/sparta/rchive/domain/post/exception/PostExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/post/repository/TutorRepository.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/main/java/kr/sparta/rchive/domain/post/service/TutorService.java
  src/main/java/kr/sparta/rchive/domain/user/entity/Track.java
Labels: enhancement

#185 [#184] [#186] Post: 게시물 open/close 단건이 아닌 복수건 처리할 수 있도록 수정 및 content 위치 변경
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/PostOpenCloseReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetSinglePostRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/TutorRes.java
  src/main/java/kr/sparta/rchive/domain/post/entity/Content.java
  src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
  src/main/java/kr/sparta/rchive/domain/post/repository/ContentRepository.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepository.java
  src/main/java/kr/sparta/rchive/domain/post/service/ContentService.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/main/java/kr/sparta/rchive/domain/post/service/TutorService.java
Labels: refactor

#188 [#187] Post: 게시물 검색하는 기능 추가
  src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/TagSearchReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchRes.java
  src/main/java/kr/sparta/rchive/domain/post/enums/PostSearchTypeEnum.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
  src/main/resources/application.yml
Labels: enhancement

#190 [#189] Bookmark: 북마크 해놓은 게시물 프로필에서 확인하는 기능 추가
  src/main/java/kr/sparta/rchive/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/kr/sparta/rchive/domain/bookmark/repository/BookmarkRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/bookmark/repository/BookmarkRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/bookmark/service/BookmarkService.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostBookmarkCoreService.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetCategoryPostRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetSinglePostRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchByTagRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchRes.java
  src/main/java/kr/sparta/rchive/domain/user/controller/ProfileController.java
  src/main/java/kr/sparta/rchive/domain/user/response/ProfileResponseCode.java
Labels: enhancement

#192 [#191] Bookmark: 검색 / 조회할 때 북마크에 등록해놓은 게시물인지 체크되는 기능 추가
  src/main/java/kr/sparta/rchive/domain/bookmark/repository/BookmarkRepository.java
  src/main/java/kr/sparta/rchive/domain/bookmark/service/BookmarkService.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetSinglePostRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchByTagRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchRes.java
  src/main/java/kr/sparta/rchive/global/s3/controller/S3ImageController.java
Labels: enhancement

#197 [#196] Role: 신청 결과 쿼리문 수정
  src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepository.java
  src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
Labels: fix

#194 [#193] BackOffice: 트랙 열람 권한 상태 수락으로 변경하는 기능 추가
  src/main/java/kr/sparta/rchive/domain/backoffice/controller/BackofficeController.java
  src/main/java/kr/sparta/rchive/domain/backoffice/respoonse/BackofficeResponseCode.java
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/domain/user/entity/Track.java
  src/main/java/kr/sparta/rchive/domain/user/service/TrackService.java
Labels: enhancement

#205 [#65] CICD 작성
  .github/workflows/ci.yml
  .github/workflows/gradle.yml
  Dockerfile
  docker/docker-compose.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
Labels: enhancement
