Repository sparta-incubating/rchive-back, pull requests merged in 2024-06, with the labels that each got.

#3 [#2] feat: github actions CI 구축
  .github/workflows/ci.yml
Labels: enhancement

#4 [#2] feat: github action CI 구축 수정
  .github/workflows/ci.yml
  src/main/resources/application.yml
Labels: fix

#16 [#13] Education Data 관련 Entity 생성
  .github/ISSUE_TEMPLATE/기능-추가.md
  src/main/java/kr/sparta/rchive/domain/educationdata/entity/EducationData.java
  src/main/java/kr/sparta/rchive/domain/educationdata/entity/EducationDataTag.java
  src/main/java/kr/sparta/rchive/domain/educationdata/entity/EducationDataTagId.java
  src/main/java/kr/sparta/rchive/domain/educationdata/entity/EducationDataTrack.java
  src/main/java/kr/sparta/rchive/domain/educationdata/entity/EducationDataTrackId.java
  src/main/java/kr/sparta/rchive/domain/educationdata/entity/Tag.java
  src/main/java/kr/sparta/rchive/domain/educationdata/enums/DataTypeEnum.java
  src/main/java/kr/sparta/rchive/domain/educationdata/enums/EducationTypeEnum.java
Labels: enhancement

#20 [#18] feat(Bookmark): Bookmark 관련 Entity 추가
  .github/pull_request_template.md
  src/main/java/kr/sparta/rchive/domain/bookmark/entity/Bookmark.java
  src/main/java/kr/sparta/rchive/domain/bookmark/entity/BookmarkId.java
  src/main/java/kr/sparta/rchive/domain/educationData/entity/EducationData.java
  src/main/java/kr/sparta/rchive/domain/educationData/entity/EducationDataTag.java
  src/main/java/kr/sparta/rchive/domain/educationData/entity/EducationDataTagId.java
  src/main/java/kr/sparta/rchive/domain/educationData/entity/EducationDataTrack.java
  src/main/java/kr/sparta/rchive/domain/educationData/entity/EducationDataTrackId.java
  src/main/java/kr/sparta/rchive/domain/educationData/entity/Tag.java
  src/main/java/kr/sparta/rchive/domain/educationData/enums/DataTypeEnum.java
  src/main/java/kr/sparta/rchive/domain/educationData/enums/EducationTypeEnum.java
Labels: enhancement

#27 [#26] move(Post): EducationData 패키지명 Post로 변경
  src/main/java/kr/sparta/rchive/domain/bookmark/entity/Bookmark.java
  src/main/java/kr/sparta/rchive/domain/comment/entity/Comment.java
  src/main/java/kr/sparta/rchive/domain/core/service/CoreService.java
  src/main/java/kr/sparta/rchive/domain/post/entity/EducationData.java
  src/main/java/kr/sparta/rchive/domain/post/entity/EducationDataTag.java
  src/main/java/kr/sparta/rchive/domain/post/entity/EducationDataTagId.java
  src/main/java/kr/sparta/rchive/domain/post/entity/EducationDataTrack.java
  src/main/java/kr/sparta/rchive/domain/post/entity/EducationDataTrackId.java
  src/main/java/kr/sparta/rchive/domain/post/entity/Tag.java
  src/main/java/kr/sparta/rchive/domain/post/enums/DataTypeEnum.java
  src/main/java/kr/sparta/rchive/domain/post/enums/EducationTypeEnum.java
Labels: move

#28 [#24] Tag 검색 기능
  src/main/java/kr/sparta/rchive/domain/core/service/EducationDataTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/controller/TagCreateRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/TagCreateReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/TagSearchReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/EducationDataRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchEducationDataRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/TagSearchRes.java
  src/main/java/kr/sparta/rchive/domain/post/exception/PostCustomExeption.java
  src/main/java/kr/sparta/rchive/domain/post/exception/PostExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/post/repository/EducationDataRepository.java
  src/main/java/kr/sparta/rchive/domain/post/repository/EducationDataTagRepository.java
  src/main/java/kr/sparta/rchive/domain/post/repository/EducationDataTrackRepository.java
  src/main/java/kr/sparta/rchive/domain/post/repository/TagRepository.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
  src/main/java/kr/sparta/rchive/domain/post/service/EducationDataService.java
  src/main/java/kr/sparta/rchive/domain/post/service/EducationDataTagService.java
  src/main/java/kr/sparta/rchive/domain/post/service/EducationDataTrackService.java
  src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
  src/main/java/kr/sparta/rchive/global/security/UserDetailsImpl.java
Labels: enhancement

#30 [#29] feat: BackOffice 구성하면서 erd 수정
  src/main/java/kr/sparta/rchive/domain/user/entity/Role.java
  src/main/java/kr/sparta/rchive/domain/user/entity/User.java
  src/main/java/kr/sparta/rchive/domain/user/enums/TrackRoleEnum.java
  src/main/java/kr/sparta/rchive/domain/user/enums/UserRoleEnum.java
Labels: enhancement

#31 [#29] feat: erd 수정
  src/main/java/kr/sparta/rchive/domain/user/entity/Track.java
Labels: enhancement

#33 [#29] feat: 학습자료 erd 수정
  src/main/java/kr/sparta/rchive/domain/post/entity/EducationData.java
Labels: enhancement
