Repository sparta-incubating/rchive-back, pull requests merged in 2024-09, with the labels that each got.

#346 [#344] CICD: 서버 에러로 dev cd 중지
  .github/workflows/cicd-dev.yml
Labels: fix

#348 [#344] CICD: 서버 에러
  .github/workflows/cicd-dev.yml
Labels: fix

#347 [#345] Post: 게시물 카테고리 조회 시 조건 변경
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForUser.java
  src/test/java/kr/sparta/rchive/domain/post/service/PostServiceTest.java
Labels: refactor

#342 [#341] Test: PostRepository 테스트 코드 작성
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForUser.java
  src/test/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImplTest.java
  src/test/java/kr/sparta/rchive/domain/post/repository/PostRepositoryTest.java
  src/test/java/kr/sparta/rchive/domain/post/service/PostServiceTest.java
  src/test/java/kr/sparta/rchive/test/PostTest.java
Labels: test

#340 [#329] Test: PostService 테스트 코드 작성
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForUser.java
  src/test/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImplTest.java
  src/test/java/kr/sparta/rchive/domain/post/repository/PostRepositoryTest.java
  src/test/java/kr/sparta/rchive/domain/post/service/PostServiceTest.java
  src/test/java/kr/sparta/rchive/test/CommentTest.java
  src/test/java/kr/sparta/rchive/test/PostTest.java
  src/test/java/kr/sparta/rchive/test/TrackTest.java
  src/test/java/kr/sparta/rchive/test/TutorTest.java
Labels: test

#351 [#349] Role: 권한 수정
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/domain/user/controller/RoleController.java
  src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleGetMyRoleRes.java
  src/main/java/kr/sparta/rchive/domain/user/repository/TrackRepository.java
Labels: refactor

#354 [#350] Test: PostRepositoryCustomImpl 테스트 코드 추가 및 로직 수정
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
  src/test/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImplTest.java
  src/test/java/kr/sparta/rchive/domain/post/repository/PostRepositoryTest.java
Labels: fix, test

#355 [#350] Test: PostCustomImplTest 추가 및 액세스 토큰 시간 변경
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/global/security/JwtUtil.java
  src/test/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImplTest.java
Labels: test

#353 [#352] User: 닉네임 규정 변경
  src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdateNicknameReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserSignupReq.java
  src/main/java/kr/sparta/rchive/domain/user/entity/User.java
Labels: refactor

#356 [#350] Post: 프론트 요청으로 response 변경
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetSinglePostRes.java
Labels: refactor

#357 [#350] Post: 프론트 요청으로 로직 변경
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetSinglePostRes.java
Labels: refactor

#358 [#350] Post: 프론트 요청으로 태그 검색 시 태그 네임도 전달해 주는 방식으로 변경
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetRes.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForUser.java
  src/test/java/kr/sparta/rchive/domain/post/service/PostServiceTest.java
Labels: refactor

#360 [#350] Test: PostRepositoryCustomImpl 테스트 코드 작성
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
  src/test/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImplTest.java
Labels: test

#362 [#352] User: 닉네임 규정 변경
  src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdateNicknameReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserSignupReq.java
  src/main/java/kr/sparta/rchive/domain/user/entity/User.java
Labels: refactor

#363 [#361] Post: PostCoreService 테스트 코드 추가 및 튜터 정렬 방식 설정
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/repository/TutorRepositoryCustomImpl.java
  src/test/java/kr/sparta/rchive/domain/core/service/PostTagCoreServiceTest.java
  src/test/java/kr/sparta/rchive/test/PostTagTest.java
  src/test/java/kr/sparta/rchive/test/RoleTest.java
Labels: test

#366 [#365] Post: 게시물 thumbnail을 삭제할 때 db에도 반영되는 로직 추가
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/DeleteThumbnailReq.java
  src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
Labels: enhancement

#367 [#365] refactor(post): Post 클래스에 thumbnail 삭제 요청 시 db에서 삭제되게 하는 로직 수정
  src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
Labels: refactor

#368 [#253] Rchive: release ver1.0
  .github/workflows/cicd-dev.yml
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/DeleteThumbnailReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetSinglePostRes.java
  src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/post/repository/TutorRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/main/java/kr/sparta/rchive/domain/user/controller/RoleController.java
  src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleGetMyRoleRes.java
  src/main/java/kr/sparta/rchive/domain/user/repository/TrackRepository.java
  src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
  src/main/java/kr/sparta/rchive/global/security/JwtUtil.java
  src/test/java/kr/sparta/rchive/domain/core/service/PostTagCoreServiceTest.java
  src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForUser.java
  src/test/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImplTest.java
  src/test/java/kr/sparta/rchive/domain/post/repository/PostRepositoryTest.java
  src/test/java/kr/sparta/rchive/domain/post/service/PostServiceTest.java
  src/test/java/kr/sparta/rchive/test/CommentTest.java
  src/test/java/kr/sparta/rchive/test/PostTagTest.java
  src/test/java/kr/sparta/rchive/test/PostTest.java
  src/test/java/kr/sparta/rchive/test/RoleTest.java
  src/test/java/kr/sparta/rchive/test/TrackTest.java
  src/test/java/kr/sparta/rchive/test/TutorTest.java
Labels: release

#372 [#370] Track: TrackNameEnum Response 변경
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/domain/user/dto/TrackNameInfo.java
  src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleGetLastSelectRoleRes.java
  src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleGetTrackNameListRes.java
  src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleRes.java
  src/main/java/kr/sparta/rchive/domain/user/dto/response/UserRes.java
  src/main/java/kr/sparta/rchive/domain/user/enums/TrackNameEnum.java
  src/main/java/kr/sparta/rchive/domain/user/enums/UserRoleEnum.java
  src/main/java/kr/sparta/rchive/domain/user/service/TrackService.java
Labels: refactor

#373 [#371] Post: PostTypeEnum 한글화
  src/main/java/kr/sparta/rchive/domain/bookmark/service/BookmarkService.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/PostTypeInfo.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/DeleteThumbnailReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetPostTypeRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetSinglePostRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostModifyPreviewRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchBackOfficeRes.java
  src/main/java/kr/sparta/rchive/domain/post/enums/PostTypeEnum.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/test/java/kr/sparta/rchive/domain/core/service/PostTagCoreServiceTest.java
  src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForPM.java
  src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForUser.java
  src/test/java/kr/sparta/rchive/test/RoleTest.java
  src/test/java/kr/sparta/rchive/test/TrackTest.java
Labels: refactor

#374 [#369] Refactor: Enum 구성 변경
  src/main/java/kr/sparta/rchive/domain/bookmark/service/BookmarkService.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/PostTypeInfo.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/DeleteThumbnailReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetPostTypeRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetSinglePostRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostModifyPreviewRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostRes.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostSearchBackOfficeRes.java
  src/main/java/kr/sparta/rchive/domain/post/enums/PostTypeEnum.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/main/java/kr/sparta/rchive/domain/user/dto/TrackNameInfo.java
  src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleGetLastSelectRoleRes.java
  src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleGetTrackNameListRes.java
  src/main/java/kr/sparta/rchive/domain/user/dto/response/RoleRes.java
  src/main/java/kr/sparta/rchive/domain/user/dto/response/UserRes.java
  src/main/java/kr/sparta/rchive/domain/user/enums/TrackNameEnum.java
  src/main/java/kr/sparta/rchive/domain/user/enums/UserRoleEnum.java
  src/main/java/kr/sparta/rchive/domain/user/service/TrackService.java
  src/test/java/kr/sparta/rchive/domain/core/service/PostTagCoreServiceTest.java
  src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForPM.java
  src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForUser.java
  src/test/java/kr/sparta/rchive/test/RoleTest.java
  src/test/java/kr/sparta/rchive/test/TrackTest.java
Labels: refactor

#375 [#361] Post: PostType의 순서를 변경 및 테스트 추가
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/PostGetPostTypeRes.java
  src/main/java/kr/sparta/rchive/domain/post/enums/PostTypeEnum.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForUser.java
  src/test/java/kr/sparta/rchive/domain/post/service/PostServiceTest.java
Labels: refactor, test

#377 [#376] Post: 게시물 검색 시 태그 내용으로도 검색할 수 있도록 변경
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustom.java
  src/main/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImpl.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/test/java/kr/sparta/rchive/domain/post/repository/PostRepositoryCustomImplTest.java
  src/test/java/kr/sparta/rchive/domain/post/service/PostServiceTest.java
Labels: refactor

#383 [#382] Post: loginPeriod가 어색한 부분 selectPeriod로 변경
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForUser.java
Labels: refactor

#385 [#384] Role: userTrackRoleApprove 수정
  src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
Labels: fix

#386 [#384] Role: userTrackRoleApprove 수정
  src/main/java/kr/sparta/rchive/domain/core/service/UserTrackRoleCoreService.java
  src/main/java/kr/sparta/rchive/domain/user/service/RoleService.java
Labels: fix

#389 [#388] User: 회원가입 할 때 닉네임 임의로 설정
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserSignupReq.java
  src/main/java/kr/sparta/rchive/domain/user/entity/User.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
Labels: enhancement

#387 [#361] Test: PostTagCoreService 테스트 코드 추가
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
  src/test/java/kr/sparta/rchive/domain/core/service/PostTagCoreServiceTest.java
  src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForPM.java
  src/test/java/kr/sparta/rchive/test/PostTest.java
  src/test/java/kr/sparta/rchive/test/TrackTest.java
  src/test/java/kr/sparta/rchive/test/TutorTest.java
Labels: test

#391 [#379] User: Swagger DTO예시
  src/main/java/kr/sparta/rchive/domain/user/dto/request/AuthPhoneReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/AuthPhoneValidReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdateNicknameReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdatePasswordReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdatePhoneReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdateProfileImgReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/RoleReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/RoleRequestListReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/RoleRequestReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindEmailReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindPasswordCheckEmailReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindPasswordCheckPhoneReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindPasswordUpdateReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserLoginReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserSignupReq.java
Labels: refactor

#393 [#392] Test: postTagService 테스트 코드 추가
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostTagService.java
  src/test/java/kr/sparta/rchive/domain/post/service/PostTagServiceTest.java
  src/test/java/kr/sparta/rchive/test/PostTagTest.java
Labels: test

#395 [#394] Test: TagService 테스트 코드 작성
  src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
  src/test/java/kr/sparta/rchive/domain/post/service/TagServiceTest.java
Labels: test

#397 [#396] Post: 태그 생성 로직 변경 및 북마크 목록 조회 시 북마크 표시 확인 가능하게 변경
  src/main/java/kr/sparta/rchive/domain/bookmark/service/BookmarkService.java
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/TagCreateReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/response/TagCreateRes.java
  src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
  src/main/java/kr/sparta/rchive/domain/user/controller/ProfileController.java
  src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForPM.java
  src/test/java/kr/sparta/rchive/domain/post/service/TagServiceTest.java
Labels: refactor

#398 [#364] Test: UserController 테스트코드
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindPasswordUpdateReq.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
  src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForPM.java
  src/test/java/kr/sparta/rchive/domain/user/controller/UserControllerTest.java
  src/test/java/kr/sparta/rchive/test/UserTest.java
Labels: test

#402 [#401] Post: 태그 생성 시 중복 태그 생성되는 오류 수정 및 태그 내용으로 정렬하도록 변경
  src/main/java/kr/sparta/rchive/domain/bookmark/service/BookmarkService.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
  src/test/java/kr/sparta/rchive/domain/core/service/PostTagCoreServiceTest.java
Labels: refactor

#404 [#403] Test: TutorService 테스트 코드 작성
  src/test/java/kr/sparta/rchive/domain/post/service/TutorServiceTest.java
Labels: test

#408 [#381] Swagger: Comment Dto 예시 작성
  src/main/java/kr/sparta/rchive/domain/comment/dto/request/CommentCreateReq.java
  src/test/java/kr/sparta/rchive/domain/core/service/PostTagCoreServiceTest.java
Labels: refactor

#407 [#380] Swagger: Post 관련 Dto 예시 작성
  src/main/java/kr/sparta/rchive/domain/comment/dto/request/CommentCreateReq.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/DeleteThumbnailReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/PostCreateReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/PostOpenCloseReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/PostUpdateReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/RecentSearchKeywordReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/TagCreateReq.java
  src/main/java/kr/sparta/rchive/domain/user/controller/UserController.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/AuthPhoneReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/AuthPhoneValidReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdateNicknameReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdatePasswordReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdatePhoneReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/ProfileUpdateProfileImgReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/RoleReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/RoleRequestListReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/RoleRequestReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindEmailReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindPasswordCheckEmailReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindPasswordCheckPhoneReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserFindPasswordUpdateReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserLoginReq.java
  src/main/java/kr/sparta/rchive/domain/user/dto/request/UserSignupReq.java
  src/main/java/kr/sparta/rchive/domain/user/service/UserService.java
  src/test/java/kr/sparta/rchive/domain/core/service/PostTagCoreServiceTest.java
  src/test/java/kr/sparta/rchive/domain/post/controller/PostControllerTestForPM.java
  src/test/java/kr/sparta/rchive/domain/user/controller/UserControllerTest.java
  src/test/java/kr/sparta/rchive/test/UserTest.java
Labels: refactor

#409 [#381] Post: 테스트 코드 수정
  src/test/java/kr/sparta/rchive/domain/post/service/PostServiceTest.java
Labels: refactor

#406 [#405] Test: PostBookmarkCoreService 테스트 코드 작성
  src/main/java/kr/sparta/rchive/domain/comment/dto/request/CommentCreateReq.java
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/DeleteThumbnailReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/PostCreateReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/PostOpenCloseReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/PostUpdateReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/RecentSearchKeywordReq.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/TagCreateReq.java
  src/test/java/kr/sparta/rchive/domain/core/service/PostBookmarkCoreServiceTest.java
  src/test/java/kr/sparta/rchive/domain/core/service/PostTagCoreServiceTest.java
  src/test/java/kr/sparta/rchive/domain/post/service/PostServiceTest.java
  src/test/java/kr/sparta/rchive/test/BookmarkTest.java
Labels: test

#411 [#410] Post: 게시물 제목과 태그내용 공백 불가능하게 변경
  src/main/java/kr/sparta/rchive/domain/core/service/PostTagCoreService.java
  src/main/java/kr/sparta/rchive/domain/post/exception/PostExceptionCode.java
  src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
Labels: refactor

#415 [#413] Tag: 태그 생성 시 띄어쓰기 제거 후 저장하는 방식으로 변경
  src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
Labels: fix

#417 [#416] Post: 링크 길이 변경
  src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
Labels: refactor

#414 [#412] Test: BookmarkService 테스트 코드 작성
  src/main/java/kr/sparta/rchive/domain/bookmark/service/BookmarkService.java
  src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
  src/test/java/kr/sparta/rchive/domain/bookmark/service/BookmarkServiceTest.java
Labels: test

#418 [#413] Tag: 태그 생성 시 공백 제거
  src/main/java/kr/sparta/rchive/domain/post/service/TagService.java
Labels: refactor

#420 [#419] Role: 출력 period 내림차순
  src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepositoryCustomImpl.java
Labels: refactor

#424 [#423] Test: PostCommentCoreService 테스트 코드 추가
  src/test/java/kr/sparta/rchive/domain/core/service/PostCommentCoreServiceTest.java
Labels: test

#427 [#426] Post: 게시물 내용 업데이트 기능 추가
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/PostUpdateContentReq.java
  src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/main/java/kr/sparta/rchive/domain/user/repository/RoleRepositoryCustomImpl.java
Labels: enhancement

#428 [#426] refactor(post): 게시물 내용 업데이트 operationId 오타 수정
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
Labels: refactor

#422 [#421] Test: TutorRepositoryCustomImpl 테스트 코드 추가
  src/main/java/kr/sparta/rchive/domain/post/controller/PostController.java
  src/main/java/kr/sparta/rchive/domain/post/dto/request/PostUpdateContentReq.java
  src/main/java/kr/sparta/rchive/domain/post/entity/Post.java
  src/main/java/kr/sparta/rchive/domain/post/response/PostResponseCode.java
  src/main/java/kr/sparta/rchive/domain/post/service/PostService.java
  src/test/java/kr/sparta/rchive/domain/core/service/PostCommentCoreServiceTest.java
  src/test/java/kr/sparta/rchive/domain/post/repository/TutorRepositoryCustomImplTest.java
  src/test/java/kr/sparta/rchive/domain/post/service/TagServiceTest.java
Labels: test
